// ./src/locale/gettext/bits_locale.go.exe
// MACHINE GENERATED BY THE COMMAND ABOVE; DO NOT EDIT

package gettext

import "fmt"

const (
	CType          Category = 0
	Numeric        Category = 1
	Time           Category = 2
	Collate        Category = 3
	Monetary       Category = 4
	Messages       Category = 5
	All            Category = 6
	Paper          Category = 7
	Name           Category = 8
	Address        Category = 9
	Telephone      Category = 10
	Measurement    Category = 11
	Identification Category = 12
)

func (c Category) String() string {
	switch c {
	case CType:
		return "LC_CTYPE"
	case Numeric:
		return "LC_NUMERIC"
	case Time:
		return "LC_TIME"
	case Collate:
		return "LC_COLLATE"
	case Monetary:
		return "LC_MONETARY"
	case Messages:
		return "LC_MESSAGES"
	case All:
		return "LC_ALL"
	case Paper:
		return "LC_PAPER"
	case Name:
		return "LC_NAME"
	case Address:
		return "LC_ADDRESS"
	case Telephone:
		return "LC_TELEPHONE"
	case Measurement:
		return "LC_MEASUREMENT"
	case Identification:
		return "LC_IDENTIFICATION"
	default:
		return fmt.Sprintf("%[1]T(%[1]d)", c)
	}
}
