#!/usr/bin/env bash
# Copyright 2015 Luke Shumaker

vars=($(
	echo '#include <locale.h>' |
	cpp -M |
	sed -e 's/.*://' -e 's/\\$//' |
	xargs sed -n 's/.*#define\s*LC_\(\S\)\(\S*\).*/\1\L\2/p' |
	sed 's/Ctype/CType/'
))

printf '//'
printf ' %q' "$0" "$@"
printf '\n// MACHINE GENERATED BY THE COMMAND ABOVE; DO NOT EDIT\n\n'
cat <<EOF
// +build ignore
#include <stdio.h>
#include <locale.h>

int main(int argc, char *argv[]) {
	printf("//");
	for (int i = 0; i < argc; i++) {
		printf(" %s", argv[i]);
	}
	printf("\n// MACHINE GENERATED BY THE COMMAND ABOVE; DO NOT EDIT\n\n");

	puts("package gettext");
	puts("import \"fmt\"");
	puts("const (");
$(
	for var in "${vars[@]}"; do
		printf '\tprintf("\t%s Category = %%d\\n", LC_%s);\n' "$var" "${var^^}"
	done
	)
	puts(")");

	puts("func (c Category) String() string {");
	puts("	switch c {");
$(
	for var in "${vars[@]}"; do
		printf '\tputs("\tcase %s: return \\"LC_%s\\"");\n' "$var" "${var^^}"
	done
	)
	puts("	default: return fmt.Sprintf(\"%[1]T(%[1]d)\", c)");
	puts("	}");
	puts("}");
	
	return 0;	
}
EOF
