#!/usr/bin/env bash
# Copyright 2015 Luke Shumaker

# Environment variables we get from Postfix (see `local(8postfix)`)
vars=(
	SHELL
	HOME
	USER
	EXTENSION
	DOMAIN
	LOGNAME
	LOCAL
	ORIGINAL_RECIPIENT
	RECIPIENT
	SENDER
	CLIENT_ADDRESS
	CLIENT_HELO
	CLIENT_HOSTNAME
	CLIENT_PROTOCOL
	SASL_METHOD
	SASL_SENDER
	SASL_USERNAME
)

{
printf '//'
printf ' %q' "$0" "$@"
printf '\n// MACHINE GENERATED BY THE COMMAND ABOVE; DO NOT EDIT\n\n'

echo package postfixpipe
echo 'import "os"'

echo 'type env struct {'
for var in "${vars[@]}"; do
	echo "$var string"
done
echo '}'

echo 'func getEnv() env {'
echo 'return env{'
for var in "${vars[@]}"; do
	echo "$var: os.Getenv(\"$var\"),"
done
echo '}'
echo '}'

for var in "${vars[@]}"; do
	echo "func (m Message) $var() string { return m.env.$var }"
done

} | gofmt

#func OriginalRecipient() string {
#	recipient := os.Getenv("ORIGINAL_RECIPIENT")
#	if recipient == "" {
#		recipient = os.Getenv("RECIPIENT")
#	}
#	return recipient
#}
