#!/usr/bin/env bash
# Copyright 2015 Luke Shumaker

sysexits_h=$1
{
	printf '//'
	printf ' %q' "$0" "$@"
	printf '\n// MACHINE GENERATED BY THE COMMAND ABOVE; DO NOT EDIT\n\n'

	declare -i n=0
	IFS=
	< "$sysexits_h" \
	sed -r -e 's/#define EX_([^_]\S+)\s/EX_\1 Sysexit = /' -e '/#/d' |
	while read -r line; do
		if [[ "$line" == " */" ]]; then
			n+=1
		elif [[ "$line" != "/*" ]]; then
			echo "$line"
		fi
		if [[ $n == 1 ]]; then
			echo
			echo package postfixpipe
			n+=1
		fi
		if [[ $n == 3 ]]; then
			echo 'const ('
			n+=1
		fi
	done
	echo ')'
} | sed 's|^ \*|//|' | gofmt
